Increment 15-17
AyratB/go-musthave-shortener-advanced pull request #3
Opened 2023-04-19 14:44 UTC by AyratB

2023-04-25 20:59 UTC, avhitrov requested changes
Гонки в коде. Рекомендации по организации комментариев и импортов.

2023-04-25 20:59 UTC, avhitrov commented on internal/app/handler_test.go
> +	"time"
Вообще есть одно устоявшееся правило для группировки импортов. Максимум три блока:

- 1 блок: стандартные библиотеки языка
- 2 блок: публичные пакеты с гитхаба, гитлаба, google и прочего
- 3 блок: локальные пакеты проекта.

Они разделяются пустой строкой.

2023-04-25 20:59 UTC, avhitrov commented on internal/store/memory.go
> +		mutex:     sync.RWMutex{},
Мало описать мьютекс. Необходимо оборачивать все операции чтения и записи в-из переменных и мап и прочих потоконезащищенных типов в Lock-Unlock и RLock-RUnlock. Защита данных - забота программиста, она не спрятана ни под каким капотом никакого компилятора.

2023-04-25 20:59 UTC, avhitrov commented on models/shorten.go
> +// Package models describe models.
```suggestion
// Package describes models.
```

2023-04-25 20:59 UTC, avhitrov commented on models/shorten.go
> +// ShortenRequest instance
Комментарии в духе Капитана Очевидность только загромождают текст программы. Начали описывать структуру, необходимо указать, для чего она или где используется.

2023-04-30 14:53 UTC, AyratB commented on internal/app/handler_test.go
> +	"time"
поправил

2023-04-30 14:54 UTC, AyratB commented on internal/store/memory.go
> +		mutex:     sync.RWMutex{},
добавил использование мьютекса при операциях чтения/записи в мапе

2023-04-30 14:54 UTC, AyratB commented on models/shorten.go
> +// Package models describe models.
Описал модели корректно

2023-04-30 14:54 UTC, AyratB commented on models/shorten.go
> +// ShortenRequest instance
Описал модели корректно

2023-05-03 21:35 UTC, avhitrov approved these changes
Все замечания учтены.

2023-05-04 06:56 UTC, merged